# Generated by Django 2.2.3 on 2019-07-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.SlugField()),
                ('assignment', models.SlugField()),
                ('question', models.IntegerField()),
                ('type', models.IntegerField()),
                ('target', models.IntegerField()),
                ('nclicks', models.IntegerField()),
                ('nagents', models.IntegerField()),
                ('agents', models.CharField(max_length=2500)),
                ('clicks', models.CharField(max_length=100)),
                ('dists', models.CharField(max_length=2500)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOAT.Experiment')),
            ],
        ),
    ]
