# Generated by Django 2.2.3 on 2019-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='height',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='width',
        ),
    ]
