# Generated by Django 3.0.2 on 2020-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='agents',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='experiment',
            name='max_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='experiment',
            name='min_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='experiment',
            name='questions',
            field=models.IntegerField(default=60),
        ),
    ]
