# Generated by Django 3.0.2 on 2020-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='is_protected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='key',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
