# Generated by Django 2.2.3 on 2019-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0002_auto_20190718_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='dpi',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapoint',
            name='height',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapoint',
            name='width',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
