# Generated by Django 3.0.2 on 2020-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0002_auto_20200109_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='height',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='nagents',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='width',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='pos',
            field=models.CharField(default='0,0', max_length=100),
            preserve_default=False,
        ),
    ]
