# Generated by Django 2.2.1 on 2020-01-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0003_auto_20190718_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experiments', models.ManyToManyField(to='MOAT.Experiment')),
            ],
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOAT.Worker'),
        ),
    ]
