# Generated by Django 3.0.2 on 2020-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOAT', '0003_experiment_agent_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='agent_speed',
            field=models.FloatField(default=1.0),
        ),
    ]
